import {cookies} from 'next/headers';
import {z} from 'zod';
import {config,db,rpc,supa,session,saveSession,requireAdmin,rateLimit,commerce,StoreError} from '@/lib/store/server';
export const dynamic='force-dynamic';
const email=z.string().email().max(254),uuid=z.string().uuid();
async function handle(req:Request,ctx:{params:Promise<{path:string[]}>}){try{const path=(await ctx.params).path.join('/'),url=new URL(req.url),method=req.method;const isWrite=method!=='GET';let b:Record<string,any>={};if(isWrite){const c=config(),origin=req.headers.get('origin');if(!origin||!(origin===url.origin||(c.origin&&origin===c.origin)))throw new StoreError('The request origin is not allowed.',403);if(!(req.headers.get('content-type')??'').startsWith('application/json'))throw new StoreError('JSON request required.',415);const text=await req.text();if(text.length>100000)throw new StoreError('Request is too large.',413);try{b=JSON.parse(text)}catch{throw new StoreError('Invalid request.',400)}await rateLimit(req,path)}
 const respond=(data:unknown)=>Response.json(data,{headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
 if(path==='me'){const s=await session();if(!s.user)return respond({user:null});const roles=await db('owner_roles','user_id=eq.'+s.user.id,s.token);let aal='aal1';try{aal=JSON.parse(atob(s.token!.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).aal}catch{}return respond({user:{id:s.user.id,email:s.user.email,name:s.user.user_metadata?.name,admin:roles.length>0,aal,factors:s.user.factors??[]}})}
 if(path.startsWith('auth/')){if(method!=='POST')throw new StoreError('Method not allowed.',405);const action=path.slice(5);if(action==='logout'){const s=await session();if(s.token)await supa('/auth/v1/logout',{method:'POST'},s.token);const jar=await cookies();jar.delete('tv-access');jar.delete('tv-refresh');return respond({ok:true})}if(action==='login'){const data=z.object({email,password:z.string().min(1).max(200)}).parse(b);const d=await supa('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify(data)});await saveSession(d);return respond({ok:true})}if(action==='signup'){const data=z.object({email,password:z.string().min(10).max(200),name:z.string().min(1).max(100)}).parse(b);await supa('/auth/v1/signup',{method:'POST',body:JSON.stringify({email:data.email,password:data.password,data:{name:data.name}})});return respond({message:'Check your email for a verification code, then choose “Enter an email verification code”.'})}if(action==='recover'){await supa('/auth/v1/recover',{method:'POST',body:JSON.stringify({email:email.parse(b.email)})});return respond({message:'If an account exists, you will receive a recovery code. Enter it using “Enter an email verification code”.'})}if(action==='verify'){const data=z.object({email,token:z.string().min(6).max(20),type:z.enum(['signup','recovery'])}).parse(b);const d=await supa('/auth/v1/verify',{method:'POST',body:JSON.stringify(data)});await saveSession(d);return respond({message:data.type==='recovery'?'Verified. Open Security to set a new password.':'Your email is verified.'})}const s=await session(true);if(action==='reset'){await supa('/auth/v1/user',{method:'PUT',body:JSON.stringify({password:z.string().min(10).max(200).parse(b.password)})},s.token);return respond({ok:true})}if(action==='mfa-enroll'){const d=await supa('/auth/v1/factors',{method:'POST',body:JSON.stringify({factor_type:'totp',friendly_name:'Turkvanta owner'})},s.token);return respond(d)}if(action==='mfa-verify'){const factor=uuid.parse(b.factor_id);const code=z.string().regex(/^\d{6}$/).parse(b.code);const challenge=await supa('/auth/v1/factors/'+factor+'/challenge',{method:'POST',body:'{}'},s.token);const d=await supa('/auth/v1/factors/'+factor+'/verify',{method:'POST',body:JSON.stringify({challenge_id:challenge.id,code})},s.token);await saveSession(d);return respond({ok:true})}throw new StoreError('Unknown account action.',404)}
 if(path==='contact'&&method==='POST'){const data=z.object({name:z.string().min(1).max(100),email,subject:z.string().max(100),message:z.string().min(10).max(3000),website:z.string().optional()}).parse(b);if(data.website)return respond({ok:true});await db('support_inquiries','',undefined,'POST',{name:data.name,email:data.email,subject:data.subject,message:data.message},true);return respond({ok:true})}
 if(path==='newsletter'&&method==='POST'){const data=z.object({email,consent:z.literal(true)}).parse(b);await db('newsletter_subscriptions','on_conflict=email',undefined,'POST',{email:data.email,consent:true},true);return respond({ok:true})}
 if(path==='shipping'&&method==='GET')return respond({zones:await db('shipping_zones','enabled=eq.true&select=id,name,fee')});
 if(path==='reviews'){if(method==='GET'){const product=uuid.parse(url.searchParams.get('product'));return respond({reviews:await db('reviews','product_id=eq.'+product+'&approved=eq.true&select=display_name,rating,body')})}const s=await session(true);const data=z.object({product_id:uuid,rating:z.number().int().min(1).max(5),body:z.string().min(10).max(2000),display_name:z.string().min(1).max(60)}).parse(b);await rpc('submit_review',{p_product:data.product_id,p_rating:data.rating,p_body:data.body,p_display_name:data.display_name},s.token);return respond({ok:true})}
 if(['checkout','coupon','payment/verify'].includes(path)){const s=await session();if(method!=='POST')throw new StoreError('Method not allowed.',405);const jar=await cookies();let guest=jar.get('tv-guest')?.value;if(path==='checkout'&&!guest){guest=crypto.randomUUID()+crypto.randomUUID();jar.set('tv-guest',guest,{httpOnly:true,secure:true,sameSite:'lax',path:'/api/store',maxAge:60*60*24*7})}const data=await commerce(path==='payment/verify'?'verify':path,{...b,guest_token:guest},s.token);return respond(data)}
 if(path==='profile'&&method==='POST'){const s=await session(true);const name=z.string().min(1).max(100).parse(b.name);await supa('/auth/v1/user',{method:'PUT',body:JSON.stringify({data:{name}})},s.token);await db('profiles','id=eq.'+s.user.id,s.token,'PATCH',{name});return respond({ok:true})}
 if(path==='saved'){const s=await session(true);if(method==='GET'){const rows=await db('saved_items','user_id=eq.'+s.user.id,s.token);return respond(rows[0]??{cart:[],wishlist:[]})}const data=z.object({cart:z.array(z.object({productId:uuid,variant:z.string().max(100),quantity:z.number().int().min(1).max(999)})).max(100),wishlist:z.array(uuid).max(500)}).parse(b);await db('saved_items','on_conflict=user_id',s.token,'POST',{user_id:s.user.id,...data});return respond({ok:true})}
 if(path==='addresses'){const s=await session(true);if(method==='GET')return respond({addresses:await db('addresses','user_id=eq.'+s.user.id,s.token)});if(method==='DELETE'){await db('addresses','id=eq.'+uuid.parse(b.id)+'&user_id=eq.'+s.user.id,s.token,'DELETE');return respond({ok:true})}const data=z.object({label:z.string().min(1).max(80),address:z.string().min(1).max(500),city:z.string().min(1).max(100),phone:z.string().min(5).max(30)}).parse(b);await db('addresses','',s.token,'POST',{user_id:s.user.id,...data});return respond({ok:true})}
 if(path==='orders'&&method==='GET'){const s=await session(true);return respond({orders:await db('orders','user_id=eq.'+s.user.id+'&select=*,items:order_items(*)&order=created_at.desc',s.token)})}
 if(path==='returns'&&method==='POST'){const s=await session(true);await rpc('request_return',{p_order:uuid.parse(b.order_id),p_reason:z.string().min(10).max(2000).parse(b.reason)},s.token);return respond({ok:true})}
 if(path.startsWith('admin/')){const s=await requireAdmin(),kind=path.slice(6);const tables:Record<string,string>={products:'products',orders:'orders',reviews:'reviews',inquiries:'support_inquiries',returns:'return_requests',coupons:'coupons',audit:'audit_events',customers:'profiles',notifications:'notification_jobs',shipping:'shipping_zones'};if(method==='GET'&&tables[kind])return respond({rows:await db(tables[kind],'select=*&order=created_at.desc&limit=500',s.token)});if(kind==='products'&&method==='POST'){const p=z.object({id:uuid,slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),name:z.string().min(1).max(150),category:z.enum(['tech-audio','home-living','style-carry','everyday-essentials']),price:z.number().int().positive().max(100000000),stock:z.number().int().min(0).max(1000000),image:z.string().refine(v=>/^\/images\/[a-z0-9_-]+\.webp$/.test(v)||/^https:\/\//.test(v)),description:z.string().max(3000),colors:z.array(z.string().min(1).max(80)).min(1).max(20),published:z.boolean(),featured:z.boolean().optional(),badge:z.string().max(30).optional(),specs:z.record(z.string()).optional()}).parse(b.product);await rpc('save_product',{p_product:p},s.token);return respond({ok:true})}if(kind==='settings'&&method==='POST'){const data=z.object({announcement:z.string().max(100),heroTitle:z.string().min(1).max(100),heroSubtitle:z.string().max(250),email,phone:z.string().max(30),shippingFee:z.number().int().min(0),pickup:z.boolean()}).parse(b.settings);await db('store_settings','id=eq.main',s.token,'PATCH',{value:data});return respond({ok:true})}if(kind==='orders'&&method==='POST'){await rpc('update_fulfillment',{p_order:uuid.parse(b.id),p_status:z.enum(['unfulfilled','processing','shipped','delivered','cancelled']).parse(b.status),p_tracking:z.string().max(150).parse(b.tracking??'')},s.token);return respond({ok:true})}if(kind==='refund'&&method==='POST'){return respond(await commerce('refund',{order_id:uuid.parse(b.order_id),reason:z.string().min(5).max(500).parse(b.reason)},s.token))}if(kind==='reviews'&&method==='POST'){await db('reviews','id=eq.'+uuid.parse(b.id),s.token,'PATCH',{approved:z.boolean().parse(b.approved)});return respond({ok:true})}if(kind==='returns'&&method==='POST'){await db('return_requests','id=eq.'+uuid.parse(b.id),s.token,'PATCH',{status:z.enum(['under_review','approved','rejected','received']).parse(b.status)});return respond({ok:true})}if(kind==='coupons'&&method==='POST'){const data=z.object({code:z.string().regex(/^[A-Z0-9_-]{3,30}$/),percent:z.number().int().min(1).max(90),minimum:z.number().int().min(0),max_uses:z.number().int().positive(),expires_at:z.string().datetime()}).parse(b);await db('coupons','on_conflict=code',s.token,'POST',data);return respond({ok:true})}if(kind==='shipping'&&method==='POST'){const data=z.object({name:z.string().min(1).max(100),fee:z.number().int().min(0),enabled:z.boolean()}).parse(b);await db('shipping_zones','',s.token,'POST',data);return respond({ok:true})}}
 throw new StoreError('This action is not available.',404);
 }catch(e){const status=e instanceof StoreError?e.status:e instanceof z.ZodError?400:500;const error=e instanceof StoreError?e.message:e instanceof z.ZodError?'Please check the form details and try again.':'Something went wrong. Please try again.';return Response.json({error},{status,headers:{'Cache-Control':'no-store'}})}}
export const GET=handle;export const POST=handle;export const DELETE=handle;
