// Supabase Edge Function. Deploy with verify_jwt=false: webhook and guests need explicit auth below.
import {createClient} from 'npm:@supabase/supabase-js@2';
import {validateTransaction,sameToken as equal} from './payment-rules.mjs';
const url=Deno.env.get('SUPABASE_URL')!;
const injected=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')??'{}');
const secret=Deno.env.get('STORE_SUPABASE_SECRET_KEY')??injected.default??Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
const db=createClient(url,secret,{auth:{persistSession:false}});
const payKey=Deno.env.get('PAYSTACK_SECRET_KEY')??'';
const origin=Deno.env.get('APP_ORIGIN')??'';
const enc=new TextEncoder();
async function sha(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(v)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
function response(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
async function rpc(name:string,args:Record<string,unknown>={}){const {data,error}=await db.rpc(name,args);if(error)throw new Error(error.message);return data}
async function pay(path:string,body?:unknown){if(!payKey)throw new Error('Payment provider is not connected.');if(Deno.env.get('PAYMENT_ENV')!=='live'&&!payKey.startsWith('sk_test_'))throw new Error('Use a test key until live payments are explicitly enabled.');const r=await fetch('https://api.paystack.co/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+payKey,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok||!d.status)throw new Error(d.message??'Payment provider unavailable');return d.data}
async function verify(reference:string){await db.from('orders').update({payment_checked_at:new Date().toISOString()}).eq('reference',reference);const d=await pay('transaction/verify/'+encodeURIComponent(reference));const status=validateTransaction(reference,Deno.env.get('PAYMENT_ENV')==='live'?'live':'test',d);if(status!=='paid')return {status,message:status==='pending'?'Your payment is still pending.':'Payment was not completed. Your bag has been kept.'};return rpc('complete_payment',{p_reference:reference,p_amount:d.amount,p_currency:d.currency,p_provider_id:String(d.id),p_event:'charge.success'})}
async function lookup(reference:string){const {data,error}=await db.from('orders').select('*').eq('reference',reference).single();if(error||!data)throw new Error('Order not found.');return data}
async function authorize(token:string|undefined){if(!token)return null;const {data,error}=await db.auth.getUser(token);if(error||!data.user)throw new Error('Please sign in again.');return data.user}
async function limit(req:Request,action:string){const key=await sha((req.headers.get('x-forwarded-for')??'unknown')+':'+action);const ok=await rpc('take_rate_limit',{p_key:key,p_limit:40});if(!ok)throw new Error('Too many requests. Please try again shortly.')}
async function notifications(){const jobs=await rpc('claim_notifications');for(const job of jobs){try{const emailKey=Deno.env.get('RESEND_API_KEY'),from=Deno.env.get('EMAIL_FROM');if(!emailKey||!from)throw new Error('Email sender is not configured');const ref=String(job.payload.reference??'your order');const kind=job.kind==='paid'?'Payment confirmed':job.kind==='shipment'?'Your order has an update':job.kind==='refund'?'Your refund is confirmed':'Your payment needs a little review';const status=String(job.payload.status??'');const text=`${kind}\n\nHello from Jedi’s Store,\n\nOrder: ${ref}\n${status?`Status: ${status}\n`:''}${job.kind==='paid'?`Amount: GHS ${(Number(job.payload.amount)/100).toFixed(2)}\n`:''}\nQuestions? Contact turkinnovation@gmail.com or 055 459 8191.\n\nJEDI’S STORE — Everyday, elevated.`;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+emailKey,'Content-Type':'application/json','Idempotency-Key':job.dedupe_key},body:JSON.stringify({from,to:[job.email],subject:kind+' · '+ref,text})});if(!r.ok)throw new Error('Email provider did not accept the notification');await db.from('notification_jobs').update({status:'sent',last_error:null}).eq('id',job.id)}catch(e){await db.from('notification_jobs').update({status:'pending',last_error:(e as Error).message,next_attempt_at:new Date(Date.now()+Math.min(3600,60*2**job.attempts)*1000).toISOString()}).eq('id',job.id)}}return jobs.length}
async function reconcileRefunds(){const {data:events}=await db.from('refund_event_inbox').select('*').eq('processed',false).order('created_at').limit(40);for(const event of events??[]){let {data:refund}=await db.from('refunds').select('*').eq('provider_id',event.provider_id).maybeSingle();if(!refund&&event.reference){const {data:order}=await db.from('orders').select('id').eq('reference',event.reference).maybeSingle();if(order){const {data:pending}=await db.from('refunds').select('*').eq('order_id',order.id).is('provider_id',null).maybeSingle();if(pending&&pending.amount===event.amount){const {error}=await db.from('refunds').update({provider_id:event.provider_id}).eq('id',pending.id);if(!error)refund=pending;}}}if(refund){await rpc('complete_refund',{p_refund:refund.id,p_amount:event.amount});await db.from('refund_event_inbox').update({processed:true}).eq('provider_id',event.provider_id);}}}
Deno.serve(async req=>{try{
 if(req.method!=='POST')return response({error:'POST required'},405);
 const raw=await req.text();if(raw.length>100000)return response({error:'Request too large'},413);
 // Webhooks are authenticated by a signature over the original raw bytes, not by a browser token.
 const signature=req.headers.get('x-paystack-signature');if(signature){if(!payKey)return response({error:'Provider not connected'},503);const key=await crypto.subtle.importKey('raw',enc.encode(payKey),{name:'HMAC',hash:'SHA-512'},false,['sign']);const expected=Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(raw)))).map(x=>x.toString(16).padStart(2,'0')).join('');if(!equal(signature,expected))return response({error:'Invalid signature'},401);const event=JSON.parse(raw);if(event.event==='charge.success'){await verify(event.data.reference)}else if(event.event==='refund.processed'){const providerId=String(event.data.id);const {error}=await db.from('refund_event_inbox').upsert({provider_id:providerId,amount:event.data.amount,reference:event.data.transaction?.reference??null},{onConflict:'provider_id',ignoreDuplicates:true});if(error)throw new Error(error.message);await reconcileRefunds();}return response({received:true})}
 const b=JSON.parse(raw);const action=String(b.action??'');
 if(action==='scheduled'){const scheduler=Deno.env.get('SCHEDULER_SECRET');if(!scheduler||!equal(req.headers.get('x-scheduler-secret')??'',scheduler))return response({error:'Unauthorized'},401);await rpc('expire_reservations');const {data:pending}=await db.from('orders').select('reference').in('payment_status',['pending','expired']).gt('created_at',new Date(Date.now()-86400000).toISOString()).order('payment_checked_at',{ascending:true}).limit(40);for(const order of pending??[]){try{await verify(order.reference)}catch{}}await reconcileRefunds();const sent=await notifications();return response({processed:sent})}
 await limit(req,action);
 const auth=req.headers.get('authorization')?.replace(/^Bearer /i,'');const user=await authorize(auth?.startsWith('eyJ')?auth:undefined);
 if(action==='coupon')return response({discount:await rpc('quote_coupon',{p_code:String(b.code??''),p_items:b.items})});
 if(action==='verify'){const order=await lookup(String(b.reference));const guest=b.guest_token?await sha(String(b.guest_token)):'';if(!(user&&order.user_id===user.id)&&!(guest&&equal(order.guest_hash??'',guest)))return response({error:'Order access could not be verified.'},403);return response(await verify(order.reference))}
 if(action==='checkout'){
 if(Deno.env.get('STORE_LIVE')!=='true')return response({error:'Checkout has not opened yet.'},503);
 if(!origin.startsWith('https://'))throw new Error('The store URL has not been configured.');
 if(!Array.isArray(b.items)||b.items.length<1||b.items.length>100)throw new Error('Please check your shopping bag.');
 const d=b.details??{};if(typeof d.email!=='string'||!/^\S+@\S+\.\S+$/.test(d.email)||typeof d.address!=='string'||d.address.length<3||typeof d.city!=='string'||typeof d.phone!=='string')throw new Error('Please check your contact and delivery details.');
 const guestToken=String(b.guest_token??'');if(!user&&guestToken.length<32)throw new Error('Guest checkout access is missing. Please retry.');
 const order=await rpc('create_checkout',{p_user:user?.id??null,p_email:user?.email??d.email,p_items:b.items,p_address:{first_name:String(d.first_name??'').slice(0,100),last_name:String(d.last_name??'').slice(0,100),address:d.address.slice(0,500),city:d.city.slice(0,100),phone:d.phone.slice(0,30),gps:String(d.gps??'').slice(0,40),instructions:String(d.instructions??'').slice(0,500),delivery:b.delivery},p_zone:b.delivery==='pickup'?null:b.zone,p_pickup:b.delivery==='pickup',p_coupon:String(b.coupon??''),p_key:b.idempotency_key,p_guest_hash:user?null:await sha(guestToken)});
 const {data:attempt}=await db.from('payment_attempts').select('*').eq('order_id',order.id).maybeSingle();if(attempt?.authorization_url)return response({authorization_url:attempt.authorization_url,reference:order.reference});
 try{const transaction=await pay('transaction/initialize',{email:order.email,amount:order.total,currency:order.currency,reference:order.reference,callback_url:origin+'/checkout',metadata:{order_id:order.id}});const {error}=await db.from('payment_attempts').upsert({order_id:order.id,reference:order.reference,authorization_url:transaction.authorization_url},{onConflict:'order_id',ignoreDuplicates:true});if(error)throw new Error(error.message);return response({authorization_url:transaction.authorization_url,reference:order.reference})}catch(e){const {data:existing}=await db.from('payment_attempts').select('authorization_url').eq('order_id',order.id).maybeSingle();if(existing?.authorization_url)return response(existing);throw e}
 }
 if(action==='refund'){
 if(Deno.env.get('STORE_LIVE')!=='true')return response({error:'Refund processing is not active.'},503);
 if(!user)return response({error:'Owner sign-in required'},401);const client=createClient(url,Deno.env.get('SUPABASE_PUBLISHABLE_KEY')??JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')??'{}').default,{global:{headers:{Authorization:'Bearer '+auth}},auth:{persistSession:false}});const {data:owner}=await client.rpc('is_owner');if(!owner)return response({error:'Owner MFA required'},403);
 const request=await rpc('prepare_refund',{p_order:b.order_id,p_actor:user.id,p_reason:String(b.reason??'Owner-approved full refund')});
 if(!request.submit)return response({status:request.status,message:'This refund already has an intent. Reconcile pending or ambiguous provider responses before taking any further action.'});
 try{const order=await lookup(request.reference);const refund=await pay('refund',{transaction:order.reference,amount:request.amount,merchant_note:request.reason});await db.from('refunds').update({provider_id:String(refund.id),status:'pending'}).eq('id',request.id);return response({status:'pending'});}catch(e){await db.from('refunds').update({status:'needs_reconciliation'}).eq('id',request.id);throw e}
 }
 return response({error:'Unknown action'},404);
 }catch(e){return response({error:(e as Error).message},400)}});
