'use client';
import {FieldSelect} from './fields';
import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
import {ArrowRight,Package,LogOut,UserRound,MapPin,ShieldCheck,Download,Heart,LayoutDashboard,Truck,Wallet,ChevronRight,LoaderCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {money} from '@/lib/store/catalog';
import type {StoreOrder} from '@/lib/store/types';
import {useStore,api} from './provider';
import {OrderBadge,OrderPaymentStatus,OrderProgress} from './order-progress';
import {TwoStepVerification} from './owner-access';

export function AccountView(){
 const s=useStore();
 const [mode,setMode]=useState('login'),[busy,setBusy]=useState(false),[note,setNote]=useState('');
 async function auth(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNote('');try{const d=await api('auth/'+mode,Object.fromEntries(new FormData(e.currentTarget)));setNote(d.message??'');await s.refreshUser();if(mode==='login')toast.success('Welcome back.')}catch(e){setNote((e as Error).message)}finally{setBusy(false)}}
 if(!s.user&&s.userLoading)return <div className="wrap inner-page"><p className="notice" role="status">Checking your session…</p></div>;
 if(!s.user&&s.userError)return <div className="wrap inner-page"><p className="notice" role="alert">{s.userError}</p><button className="button secondary" onClick={()=>s.refreshUser()}>Check account again</button></div>;
 if(!s.user)return <div className="wrap"><div className="auth-layout"><div className="auth-story"><span className="eyebrow">YOUR OWN LITTLE CORNER</span><h1>Good to<br/>have you here.</h1><p>Your favourites. Your orders.<br/>Your everyday, all together.</p></div><div className="auth-form"><h2>{mode==='login'?'Welcome back.':mode==='signup'?'Make yourself at home.':mode==='verify'?'Check your inbox.':mode==='reset'?'Set a new password.':'Forgot your password?'}</h2>{!s.configured&&<div className="notice">Accounts will open when the store launches. You can explore the collection and save favourites now.</div>}{note&&<p className="notice" role="status">{note}</p>}<form onSubmit={auth}>{mode==='signup'&&<label>Your name<input name="name" autoComplete="name" required/></label>}{mode!=='reset'&&<label>Email address<input name="email" type="email" autoComplete="email" required/></label>}{(mode==='login'||mode==='signup'||mode==='reset')&&<label>Password<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?undefined:10}/></label>}{mode==='verify'&&<><label>Email verification code<input name="token" inputMode="numeric" autoComplete="one-time-code" required/></label><label>Code type<FieldSelect name="type" defaultValue="signup" options={[{value:"signup",label:"New account"},{value:"recovery",label:"Password recovery"}]}/></label></>}<button className="button" disabled={!s.configured||busy}>{busy?'One moment…':mode==='login'?'Sign in':mode==='signup'?'Create account':mode==='verify'?'Verify code':mode==='reset'?'Update password':'Send recovery code'}<ArrowRight size={18}/></button></form><button className="auth-switch" onClick={()=>{setMode(mode==='login'?'signup':'login');setNote('')}}>{mode==='login'?'New here? Create an account':'Already have an account? Sign in'}</button><br/><button className="auth-switch" onClick={()=>setMode('recover')}>Forgot your password?</button><br/><button className="auth-switch" onClick={()=>setMode('verify')}>Enter an email verification code</button></div></div></div>;
 return <AccountDashboard key={s.user.id}/>;
}

function OrdersTable({orders,onView}:{orders:StoreOrder[];onView:(order:StoreOrder)=>void}){
 return <Table className="customer-orders-table"><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Date</TableHead><TableHead>Status</TableHead><TableHead>Total</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{orders.map(order=><TableRow key={order.id}><TableCell><strong>{order.reference}</strong></TableCell><TableCell>{new Date(order.created_at).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</TableCell><TableCell><OrderBadge order={order}/></TableCell><TableCell className="order-money">{money(order.total)}</TableCell><TableCell><button className="text-link" onClick={()=>onView(order)}>View order <ArrowRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table>;
}

function AccountDashboard(){
 const s=useStore();
 const [tab,setTab]=useState('dashboard'),[orders,setOrders]=useState<StoreOrder[]>([]),[loading,setLoading]=useState(true),[orderError,setOrderError]=useState(''),[addressError,setAddressError]=useState(''),[signingOut,setSigningOut]=useState(false),[mfaBusy,setMfaBusy]=useState(false);
 const [addresses,setAddresses]=useState<{id:string;label:string;address:string;city:string;phone:string}[]>([]),[detail,setDetail]=useState<StoreOrder|null>(null);
 useEffect(()=>{
  let active=true;
  api('orders').then(d=>{if(active)setOrders(d.orders??[])}).catch(e=>{if(active)setOrderError(e.message)}).finally(()=>{if(active)setLoading(false)});
  api('addresses').then(d=>{if(active)setAddresses(d.addresses??[])}).catch(e=>{if(active)setAddressError(e.message)});
  return()=>{active=false};
 },[]);
 async function retryOrders(){setLoading(true);setOrderError('');try{const d=await api('orders');setOrders(d.orders??[])}catch(e){setOrderError((e as Error).message)}finally{setLoading(false)}}
 async function signOut(){if(mfaBusy||signingOut||s.userLoading)return;setSigningOut(true);try{await api('auth/logout',{});await s.refreshUser();toast.success('You’ve signed out.')}catch(e){toast.error((e as Error).message)}finally{setSigningOut(false)}}
 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api('profile',Object.fromEntries(new FormData(e.currentTarget)));toast.success('Your profile has been updated.');await s.refreshUser()}catch(e){toast.error((e as Error).message)}}
 async function addAddress(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api('addresses',Object.fromEntries(new FormData(e.currentTarget)));const d=await api('addresses');setAddresses(d.addresses??[]);setAddressError('');toast.success('Address saved.')}catch(e){toast.error((e as Error).message)}}
 if(!s.user)return null;
 const firstName=s.user.name?.trim().split(/\s+/)[0]||'there';
 const initials=(s.user.name||s.user.email).trim().slice(0,1).toUpperCase();
 const latest=orders[0];
 const paidTotal=orders.filter(order=>order.payment_status==='paid').reduce((total,order)=>total+order.total,0);
 const nav=[{value:'dashboard',label:'Dashboard',Icon:LayoutDashboard},{value:'orders',label:'Orders',Icon:Package},{value:'addresses',label:'Addresses',Icon:MapPin},{value:'profile',label:'Account details',Icon:UserRound},{value:'security',label:'Security',Icon:ShieldCheck}];
 const orderPlaceholder=loading?<div className="customer-empty" role="status"><LoaderCircle size={24} className="spin"/><p>Loading your orders…</p></div>:orderError?<div className="customer-empty" role="alert"><p>{orderError}</p><button className="button secondary" onClick={retryOrders}>Try again</button></div>:<div className="customer-empty"><Package size={36} aria-hidden="true"/><h3>Your next favourite is waiting.</h3><p>Your orders will appear here after your first purchase.</p><Link href="/shop" className="button">Explore the collection <ArrowRight size={17}/></Link></div>;
 return <div className="wrap inner-page customer-account">
  <div className="breadcrumbs"><Link href="/">Home</Link><ChevronRight size={14} aria-hidden="true"/><span>My account</span></div>
  <div className="customer-page-heading"><h1>My account</h1><p>Your orders, favourites, and everyday details.</p>{s.user.admin===true&&<a className="button account-owner-entry" href="/admin"><ShieldCheck size={18}/>Store management <ArrowRight size={18}/></a>}</div>
  <Tabs value={tab} onValueChange={setTab} orientation="vertical" className="customer-layout">
   <aside className="customer-sidebar">
    <div className="customer-identity"><span className="customer-avatar" aria-hidden="true">{initials}</span><div><strong>{s.user.name||'Your account'}</strong><span>{s.user.email}</span></div></div>
    <TabsList className="customer-navigation" aria-label="Account sections">{nav.map(({value,label,Icon})=><TabsTrigger key={value} value={value}><Icon size={19} aria-hidden="true"/>{label}</TabsTrigger>)}</TabsList>
    <div className="customer-sidebar-links"><Link href="/wishlist"><Heart size={19} aria-hidden="true"/>Wishlist <span>{s.wishlist.length}</span></Link>{s.user.admin===true&&<a href="/admin"><ShieldCheck size={19} aria-hidden="true"/>Store management</a>}<button disabled={signingOut||mfaBusy||s.userLoading} onClick={signOut}><LogOut size={19} aria-hidden="true"/>{signingOut?'Signing out…':'Sign out'}</button></div>
   </aside>
   <div className="customer-main">
    <TabsContent value="dashboard" className="customer-tab">
     <section className="customer-welcome"><div className="welcome-person"><span className="customer-avatar large" aria-hidden="true">{initials}</span><div><p>Welcome back,</p><h2>{firstName}.</h2><span>Make yourself at home.</span></div></div><div className="customer-stats"><div><span className="customer-stat-icon"><Package size={21} aria-hidden="true"/></span><span>Orders shown<strong>{loading||orderError?'—':orders.length}</strong></span></div><div><span className="customer-stat-icon"><Wallet size={21} aria-hidden="true"/></span><span>Paid order total<strong>{loading||orderError?'—':money(paidTotal)}</strong></span></div><Link href="/wishlist"><span className="customer-stat-icon"><Heart size={21} aria-hidden="true"/></span><span>Wishlist<strong>{s.wishlist.length}</strong></span></Link></div></section>
     <div className="customer-quick-grid">
      <button className="customer-quick-card" onClick={()=>setTab('orders')}><span className="customer-action-icon"><Package size={23} aria-hidden="true"/></span><strong>View orders</strong><span>Order details and receipts.</span><ArrowRight size={19} aria-hidden="true"/></button>
      <button className="customer-quick-card" onClick={()=>latest&&!loading&&!orderError?setDetail(latest):setTab('orders')}><span className="customer-action-icon"><Truck size={23} aria-hidden="true"/></span><strong>Track an order</strong><span>Follow your delivery progress.</span><ArrowRight size={19} aria-hidden="true"/></button>
      <button className="customer-quick-card" onClick={()=>setTab('addresses')}><span className="customer-action-icon"><MapPin size={23} aria-hidden="true"/></span><strong>Manage addresses</strong><span>Keep your delivery details handy.</span><ArrowRight size={19} aria-hidden="true"/></button>
      <button className="customer-quick-card" onClick={()=>setTab('security')}><span className="customer-action-icon"><ShieldCheck size={23} aria-hidden="true"/></span><strong>Account security</strong><span>Password and two-step verification.</span><ArrowRight size={19} aria-hidden="true"/></button>
     </div>
     <div className="customer-dashboard-grid"><section className="customer-panel"><div className="customer-panel-heading"><h2>Recent orders</h2><button className="text-link" onClick={()=>setTab('orders')}>View all <ArrowRight size={16}/></button></div>{!loading&&!orderError&&orders.length?<OrdersTable orders={orders.slice(0,4)} onView={setDetail}/>:orderPlaceholder}</section>
      <section className="customer-panel latest-order"><div className="customer-panel-heading"><h2>Your latest order</h2><Truck size={23} aria-hidden="true"/></div>{loading?<p role="status">Loading delivery updates…</p>:orderError?<p>Delivery updates are unavailable. Try loading your orders again.</p>:latest?<><div className="latest-order-reference"><strong>{latest.reference}</strong><OrderBadge order={latest}/></div><p className="muted">Placed on {new Date(latest.created_at).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</p><OrderPaymentStatus order={latest}/><OrderProgress order={latest}/><button className="text-link" onClick={()=>setDetail(latest)}>View order details <ArrowRight size={16}/></button></>:<div className="customer-empty"><Truck size={34} aria-hidden="true"/><p>Your delivery progress will appear here after your first order.</p></div>}</section>
     </div>
    </TabsContent>
    <TabsContent value="orders" className="customer-tab"><section className="customer-panel"><div className="customer-panel-heading"><div><h2>Your orders</h2><p>View payment details, delivery updates, and receipts.</p></div></div>{!loading&&!orderError&&orders.length?<OrdersTable orders={orders} onView={setDetail}/>:orderPlaceholder}</section></TabsContent>
    <TabsContent value="profile" className="customer-tab"><section className="customer-panel"><div className="customer-panel-heading"><div><h2>Account details</h2><p>A few details that make your account yours.</p></div></div><form className="form-grid settings-form" onSubmit={saveProfile}><label className="span-2">Full name<input name="name" defaultValue={s.user.name} required maxLength={100}/></label><label className="span-2">Email<input value={s.user.email} disabled/></label><button className="button">Save profile</button></form></section></TabsContent>
    <TabsContent value="addresses" className="customer-tab"><section className="customer-panel"><div className="customer-panel-heading"><h2>Your addresses</h2><MapPin size={23} aria-hidden="true"/></div>{addressError&&<p className="notice" role="alert">{addressError}</p>}<div className="form-grid">{addresses.map(a=><div className="account-card" key={a.id}><h3>{a.label}</h3><p>{a.address}, {a.city}</p><p>{a.phone}</p><button className="text-link" onClick={async()=>{try{await api('addresses',{id:a.id},'DELETE');setAddresses(old=>old.filter(x=>x.id!==a.id));toast.success('Address removed.')}catch(error){toast.error((error as Error).message)}}}>Remove address</button></div>)}</div><form className="form-grid settings-form" onSubmit={addAddress}><h2 className="span-2">Save an address</h2><label>Label<input name="label" placeholder="Home" required/></label><label>Phone<input name="phone" type="tel" required/></label><label className="span-2">Address<input name="address" required/></label><label>City<input name="city" required/></label><button className="button">Save address</button></form></section></TabsContent>
    <TabsContent value="security" className="customer-tab"><section className="customer-panel"><div className="customer-panel-heading"><h2>Account security</h2><ShieldCheck size={23} aria-hidden="true"/></div><div className="account-card"><h3>Update your password</h3><form className="form-grid settings-form" onSubmit={async e=>{e.preventDefault();try{await api('auth/reset',Object.fromEntries(new FormData(e.currentTarget)));toast.success('Password updated.')}catch(e){toast.error((e as Error).message)}}}><label>New password<input type="password" name="password" minLength={10} required autoComplete="new-password"/></label><button className="button">Update password</button></form></div><div className="account-card"><h3>Two-step verification</h3><TwoStepVerification onBusyChange={setMfaBusy}/></div>{s.user.admin===true&&<a className="button" href="/admin">Open store management <ArrowRight size={18}/></a>}</section></TabsContent>
   </div>
  </Tabs>
  <Dialog open={!!detail} onOpenChange={()=>setDetail(null)}><DialogContent className="product-editor customer-order-dialog"><DialogTitle>Order {detail?.reference}</DialogTitle><DialogDescription>Payment and delivery are tracked separately.</DialogDescription>{detail&&<><OrderBadge order={detail}/><OrderPaymentStatus order={detail}/><OrderProgress order={detail}/>{detail.items?.map((i,n)=><div className="summary-line" key={n}><span>{i.name} × {i.quantity}</span><strong>{money(i.unit_price*i.quantity)}</strong></div>)}<div className="summary-line"><strong>Total</strong><strong>{money(detail.total)}</strong></div><button className="button secondary" onClick={()=>window.print()}><Download size={16}/>Print receipt</button><form className="stack" onSubmit={async e=>{e.preventDefault();try{await api('returns',{order_id:detail.id,reason:new FormData(e.currentTarget).get('reason')});toast.success('Return request received. Our team will review it.')}catch(e){toast.error((e as Error).message)}}}><p className="small muted">Return requests are available for paid orders marked as delivered.</p><label>Request a return<textarea name="reason" minLength={10} maxLength={2000} required placeholder="Tell us what happened"/></label><button className="button" disabled={detail.payment_status!=='paid'||detail.fulfillment_status!=='delivered'}>Submit return request</button></form></>}</DialogContent></Dialog>
 </div>;
}
