'use client';
import Link from 'next/link';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useSearchParams} from 'next/navigation';
import {ArrowRight,ArrowLeft,ChevronRight,ShoppingBag,ShieldCheck,Truck,Package,Headphones,LockKeyhole,MapPin,Check,LoaderCircle,CheckCircle2,CircleAlert,Tag} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import {FieldSelect} from './fields';
import {useStore,api} from './provider';
import {money} from '@/lib/store/catalog';

const steps=[{label:'Contact',description:'Your details & address'},{label:'Delivery',description:'Choose how it arrives'},{label:'Review & pay',description:'Confirm your order'}];
const assurances=[{Icon:ShieldCheck,title:'Paystack checkout',text:'Payment handled securely'},{Icon:Truck,title:'Delivery in Ghana',text:'Choose a supported area'},{Icon:Package,title:'Order updates',text:'Follow progress in your account'},{Icon:Headphones,title:'Here to help',text:'Contact our store team'}];
export function CheckoutView(){
 const s=useStore(),params=useSearchParams();
 const [step,setStep]=useState(1),[delivery,setDelivery]=useState('delivery'),[zone,setZone]=useState(''),[zones,setZones]=useState<{id:string;name:string;fee:number}[]>([]),[shippingLoading,setShippingLoading]=useState(s.configured),[shippingError,setShippingError]=useState('');
 const [details,setDetails]=useState<Record<string,string>>({}),[coupon,setCoupon]=useState(''),[discount,setDiscount]=useState(0),[couponBusy,setCouponBusy]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[message,setMessage]=useState(''),[termsAccepted,setTermsAccepted]=useState(false);
 const subtotal=s.cart.reduce((sum,line)=>sum+(s.products.find(p=>p.id===line.productId)?.price??0)*line.quantity,0);
 const selectedZone=zones.find(item=>item.id===zone);
 const shipping=delivery==='pickup'?0:selectedZone?.fee??0;
 const shippingKnown=delivery==='pickup'||!!selectedZone;
 const reference=params.get('reference')??params.get('trxref');
 const couponRevision=useRef(0);
 useEffect(()=>{let active=true;if(!s.configured){setShippingLoading(false);return;}setShippingLoading(true);api('shipping').then(data=>{if(active)setZones(data.zones??[])}).catch(error=>{if(active)setShippingError(error.message)}).finally(()=>{if(active)setShippingLoading(false)});return()=>{active=false};},[s.configured]);
 useEffect(()=>{let active=true;if(!reference)return;setStatus('pending');api('payment/verify',{reference}).then(data=>{if(!active)return;setStatus(data.status);setMessage(data.message??'');if(data.status==='paid')s.clearCart()}).catch(error=>{if(active){setStatus('pending');setMessage(error.message)}});return()=>{active=false};},[reference]);
 useEffect(()=>{couponRevision.current++;setDiscount(0)},[s.cart]);
 async function applyCoupon(){if(!coupon.trim()||couponBusy)return;setCouponBusy(true);const revision=couponRevision.current;try{const data=await api('coupon',{code:coupon,items:s.cart});if(revision!==couponRevision.current)return;setDiscount(data.discount);toast.success('Coupon applied. It will be checked again before payment.')}catch(error){setDiscount(0);toast.error((error as Error).message)}finally{setCouponBusy(false)}}
 async function contactNext(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget)) as Record<string,string>;setDetails({...details,...values,email:s.user?.email??values.email});setStep(2);setTermsAccepted(false)}
  async function pay(){setBusy(true);try{const fingerprint=JSON.stringify({items:s.cart,details:{...details,email:s.user?.email??details.email},delivery,zone,coupon});let key=sessionStorage.getItem('turkvanta-checkout-key');if(!key||sessionStorage.getItem('turkvanta-checkout-input')!==fingerprint){key=crypto.randomUUID();sessionStorage.setItem('turkvanta-checkout-key',key);sessionStorage.setItem('turkvanta-checkout-input',fingerprint)}const d=await api('checkout',{items:s.cart,details:{...details,email:s.user?.email??details.email},delivery,zone,coupon,idempotency_key:key});if(d.authorization_url&&new URL(d.authorization_url).hostname==='checkout.paystack.com'&&new URL(d.authorization_url).protocol==='https:'){location.assign(d.authorization_url)}else throw new Error('Payment could not be initialized. Your bag has been kept.')}catch(e){if(/no longer pending|expired|checkout changed/i.test((e as Error).message)){sessionStorage.removeItem('turkvanta-checkout-key');toast.error('That checkout expired. Please review your bag and try again.')}else toast.error((e as Error).message)}finally{setBusy(false)}}

 if(reference||status){
  const paid=status==='paid',needsReview=status==='reconciliation',failed=['failed','cancelled','expired'].includes(status);
  return <div className="wrap inner-page secure-checkout"><section className="checkout-result customer-panel"><span className="checkout-result-icon">{paid?<CheckCircle2 size={42}/>:needsReview||failed?<CircleAlert size={42}/>:<LoaderCircle size={42} className="spin"/>}</span><h1>{paid?'Thank you. Your order is confirmed.':needsReview?'Your payment is being reviewed.':failed?'Your payment wasn’t completed.':'We’re checking your payment.'}</h1><p role="status">{message||'Your order is updated only after Paystack confirms the transaction.'}</p><Link className="button" href={paid?'/account':'/cart'}>{paid?'View your orders':'Back to your bag'}<ArrowRight size={18}/></Link><Link className="text-link" href="/contact">Contact our team</Link></section></div>;
 }
 return <div className="wrap inner-page secure-checkout">
  <div className="breadcrumbs"><Link href="/">Home</Link><ChevronRight size={14} aria-hidden="true"/><Link href="/cart">Your bag</Link><ChevronRight size={14} aria-hidden="true"/><span>Checkout</span></div>
  <div className="secure-checkout-heading"><h1><span><LockKeyhole size={26} aria-hidden="true"/></span>Secure checkout</h1><p>A few details, then something good is on its way.</p></div>
  <div className="checkout-assurances">{assurances.map(({Icon,title,text})=><div key={title}><span className="assurance-icon"><Icon size={23} aria-hidden="true"/></span><span><strong>{title}</strong><small>{text}</small></span></div>)}</div>
  {!s.live&&<div className="notice"><ShieldCheck size={20}/><div><strong>You’re exploring a preview store.</strong><p>You can try the checkout steps. Orders and payments are not active yet, and your details won’t be submitted.</p></div></div>}
  {!s.cart.length?<section className="customer-panel customer-empty"><ShoppingBag size={42} aria-hidden="true"/><h2>Your bag is empty.</h2><p>Find something you love and meet us back here.</p><Link className="button" href="/shop">Explore the collection <ArrowRight size={18}/></Link></section>:<>
   <nav className="checkout-progress" aria-label="Checkout progress"><ol>{steps.map(({label,description},index)=><li key={label} className={index+1<step?'complete':index+1===step?'current':''}><button type="button" disabled={index+1>step||busy} aria-current={index+1===step?'step':undefined} onClick={()=>setStep(index+1)}><span className="checkout-step-number">{index+1<step?<Check size={20} aria-hidden="true"/>:index+1}</span><strong>{label}</strong><small>{description}</small></button></li>)}</ol></nav>
   <div className="checkout-layout"><section className="checkout-form-panel customer-panel" aria-label={steps[step-1].label}>
    <div className="checkout-panel-heading"><span>{step}</span><div><h2>{step===1?'Contact information':step===2?'Delivery options':'Review your order'}</h2><p>{step===1?'Where should we send your order and updates?':step===2?'Choose the option that works for you.':'Check the details before continuing to Paystack.'}</p></div></div>
    {step===1&&<form className="form-grid" onSubmit={contactNext}>
     <label>First name <span className="field-required">*</span><input name="first_name" autoComplete="given-name" defaultValue={details.first_name} required/></label><label>Last name <span className="field-required">*</span><input name="last_name" autoComplete="family-name" defaultValue={details.last_name} required/></label>
     <label>Email address <span className="field-required">*</span><input name="email" type="email" autoComplete="email" value={s.user?.email??details.email??''} onChange={event=>setDetails({...details,email:event.target.value})} readOnly={!!s.user} required/>{s.user&&<small className="field-help">We’ll use the email on your account.</small>}</label><label>Phone number <span className="field-required">*</span><input name="phone" type="tel" autoComplete="tel" placeholder="055 000 0000" defaultValue={details.phone} required/></label>
     <div className="checkout-field-heading span-2"><MapPin size={19} aria-hidden="true"/><h3>Delivery address</h3></div><label className="span-2">Street address <span className="field-required">*</span><input name="address" autoComplete="street-address" defaultValue={details.address} minLength={3} required/></label><label>City / town <span className="field-required">*</span><input name="city" autoComplete="address-level2" defaultValue={details.city} required/></label><label>GhanaPost GPS address <span className="muted">(optional)</span><input name="gps" placeholder="GA-000-0000" defaultValue={details.gps}/></label><label className="span-2">Delivery instructions <span className="muted">(optional)</span><textarea name="instructions" defaultValue={details.instructions} maxLength={500} placeholder="A nearby landmark or anything we should know."/></label>
     <button className="button span-2">Continue to delivery <ArrowRight size={18}/></button>
    </form>}
    {step===2&&<div className="stack checkout-delivery"><div className="delivery-choice-grid"><button type="button" className={'delivery-choice '+(delivery==='delivery'?'selected':'')} aria-pressed={delivery==='delivery'} onClick={()=>{setDelivery('delivery');setTermsAccepted(false)}}><Truck size={25} aria-hidden="true"/><span><strong>Deliver to me</strong><small>Select your area below.</small></span><span className="choice-indicator" aria-hidden="true">{delivery==='delivery'&&<Check size={15}/>}</span></button>{s.settings.pickup&&<button type="button" className={'delivery-choice '+(delivery==='pickup'?'selected':'')} aria-pressed={delivery==='pickup'} onClick={()=>{setDelivery('pickup');setTermsAccepted(false)}}><MapPin size={25} aria-hidden="true"/><span><strong>Arrange pickup</strong><small>No delivery charge.</small></span><span className="choice-indicator" aria-hidden="true">{delivery==='pickup'&&<Check size={15}/>}</span></button>}</div>
     {delivery==='delivery'&&(s.configured?<label>Delivery area <span className="field-required">*</span><FieldSelect name="zone" required value={zone} onValueChange={setZone} placeholder={shippingLoading?'Loading delivery areas…':'Select your delivery area'} options={zones.map(item=>({value:item.id,label:item.name+' · '+money(item.fee)}))}/>{shippingError?<span className="field-help" role="alert">{shippingError} Please contact our team for help.</span>:!shippingLoading&&!zones.length&&<span className="field-help">No delivery areas are currently available. Contact us or choose pickup if offered.</span>}</label>:<div className="notice">Delivery areas and rates will be confirmed before the store opens.</div>)}
     {delivery==='pickup'&&<div className="checkout-delivery-note"><MapPin size={20} aria-hidden="true"/><p>Our team will confirm the collection location and arrangements with you.</p></div>}
     <div className="checkout-form-actions"><button className="text-link" onClick={()=>setStep(1)}><ArrowLeft size={17}/>Back to contact</button><button className="button" disabled={s.configured&&delivery==='delivery'&&(!selectedZone||shippingLoading||!!shippingError)} onClick={()=>setStep(3)}>Review order <ArrowRight size={18}/></button></div>
    </div>}
    {step===3&&<div className="stack checkout-review"><div className="review-info-card"><div><h3>Contact & address</h3><button className="text-link" onClick={()=>setStep(1)}>Edit</button></div><strong>{details.first_name} {details.last_name}</strong><p>{s.user?.email??details.email}</p><p>{details.phone}</p><p>{details.address}, {details.city}</p>{details.gps&&<p>{details.gps}</p>}{details.instructions&&<p className="muted">{details.instructions}</p>}</div><div className="review-info-card"><div><h3>Delivery</h3><button className="text-link" onClick={()=>setStep(2)}>Edit</button></div><p>{delivery==='pickup'?'Arrange pickup':selectedZone?.name??'Area to be confirmed'}</p><strong>{delivery==='pickup'?'Free pickup':shippingKnown?money(shipping):'Fee to be confirmed'}</strong></div><div className="payment-provider-note"><ShieldCheck size={25} aria-hidden="true"/><div><strong>Continue securely with Paystack</strong><p>You’ll choose from the payment options available for your order on Paystack.</p></div></div><label className="checkbox-label checkout-consent"><Checkbox id="checkout-terms" checked={termsAccepted} onCheckedChange={value=>setTermsAccepted(value===true)} required/><span>I agree to the <Link href="/policies/terms" target="_blank" rel="noreferrer">store terms</Link>.</span></label><button className="button full" disabled={!s.live||busy||!termsAccepted} onClick={pay}>{busy?<LoaderCircle className="spin" size={18}/>:<LockKeyhole size={18}/>} {busy?'Opening Paystack…':s.live?'Continue to secure payment':'Payments open when the store launches'}</button><p className="small muted">{!s.live?'This preview does not create an order or take payment.':'Your order total is confirmed before payment.'}</p></div>}
   </section><aside className="order-summary checkout-order-panel"><div className="customer-panel-heading"><h2>Your order</h2><Link href="/cart" className="text-link">Edit bag</Link></div><div className="checkout-order-items">{s.cart.map(line=>{const product=s.products.find(p=>p.id===line.productId);return product?<div className="checkout-item" key={line.productId+line.variant}><img src={product.image} alt="" width="64" height="64"/><span><strong>{product.name}</strong><small>{line.variant} · Qty {line.quantity}</small></span><b>{money(product.price*line.quantity)}</b></div>:<p key={line.productId+line.variant} className="notice">An item is unavailable. Please update your bag.</p>})}</div><div className="checkout-discount"><label htmlFor="checkout-discount"><Tag size={16} aria-hidden="true"/>Have a discount code?</label><div className="coupon-form"><input id="checkout-discount" placeholder="Enter code" value={coupon} disabled={couponBusy} onChange={event=>{couponRevision.current++;setCoupon(event.target.value);setDiscount(0)}}/><button disabled={!coupon.trim()||couponBusy||!s.configured} onClick={applyCoupon}>{couponBusy?'Checking…':'Apply'}</button></div></div><div className="checkout-totals"><div className="summary-line"><span>Subtotal</span><span>{money(subtotal)}</span></div>{discount>0&&<div className="summary-line checkout-saving"><span>Discount</span><span>−{money(discount)}</span></div>}<div className="summary-line"><span>{delivery==='pickup'?'Pickup':'Delivery'}</span><span>{delivery==='pickup'?'Free':shippingKnown?money(shipping):'Select an area'}</span></div><div className="summary-line checkout-grand-total"><strong>Estimated total</strong><strong>{money(Math.max(0,subtotal-discount)+shipping)}</strong></div></div><p className="small muted">{shippingKnown?'Final taxes and charges are confirmed before payment.':'Choose your delivery area to include the delivery fee.'}</p><div className="checkout-help"><Headphones size={22} aria-hidden="true"/><div><strong>Need a hand?</strong><Link href="/contact">Talk to our team <ArrowRight size={14}/></Link></div></div></aside></div>
  </>}
 </div>;
}
