'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useState,type FormEvent} from 'react';
import {Search,Heart,ShoppingBag,UserRound,Menu,ArrowUpRight,ArrowRight,Minus,Plus,Trash2,Mail,Phone,ShieldCheck,Headphones,Package,ChevronDown} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {toast} from 'sonner';
import {brand,categories,money} from '@/lib/store/catalog';
import {useStore,api} from './provider';
import {StoreMotion} from './motion';
export function Logo({light=false}:{light?:boolean}){return <Link href="/" className={`logo ${light?'logo-light':''}`} aria-label="Jedi’s Store home"><span className="logo-mark" aria-hidden="true">J<span>•</span></span><span>{brand.name}<span className="logo-period">.</span></span></Link>}
export function StoreShell({children}:{children:React.ReactNode}){
 const s=useStore(),router=useRouter(),path=usePathname();const [mobile,setMobile]=useState(false),[query,setQuery]=useState('');const count=s.cart.reduce((a,x)=>a+x.quantity,0);
 function search(e:FormEvent){e.preventDefault();router.push('/shop?q='+encodeURIComponent(query));setMobile(false)}
 return <><a href="#main-content" className="skip-link">Skip to content</a><div className="announcement"><span>{s.settings.announcement}</span><span className="announcement-right">Thoughtfully selected. Yours to discover.</span></div><header className="site-header"><div className="header-main wrap"><button className="icon-button mobile-only" aria-label="Open menu" onClick={()=>setMobile(true)}><Menu/></button><Logo/><form className="header-search" onSubmit={search}><Search size={19}/><input aria-label="Search products" placeholder="Find your next favourite..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>↵</kbd></form><div className="header-actions"><Link className="icon-button" href="/account" aria-label="My account"><UserRound/></Link><Link className="icon-button wishlist-icon" href="/wishlist" aria-label={`Wishlist, ${s.wishlist.length} items`}><Heart/>{s.wishlist.length>0&&<span className="tiny-count">{s.wishlist.length}</span>}</Link><button className="bag-button" aria-label={`Open shopping bag, ${count} items`} onClick={()=>s.setCartOpen(true)}><ShoppingBag/><span className="bag-word">Bag</span><b key={count} className="bag-count">{count}</b></button></div></div><nav className="nav-row wrap" aria-label="Main navigation"><div><Link className={path==='/shop'?'nav-active':''} href="/shop">Shop all <ChevronDown size={14}/></Link>{categories.map(c=><Link key={c.slug} href={'/shop?category='+c.slug}>{c.name}</Link>)}<Link href="/shop?sort=new">New arrivals <span className="nav-new">NEW</span></Link></div><Link href="/about">Our story <ArrowUpRight size={15}/></Link></nav></header>
 <Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="mobile-menu"><SheetHeader><SheetTitle>Explore Jedi’s Store</SheetTitle><SheetDescription>Find a little something for your everyday.</SheetDescription></SheetHeader><form className="search-form" onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products" aria-label="Search products"/><button className="icon-button" aria-label="Search"><Search/></button></form>{[{slug:'',name:'Shop all'},...categories].map(c=><Link onClick={()=>setMobile(false)} key={c.slug} href={'/shop'+(c.slug?'?category='+c.slug:'')}>{c.name}<ArrowRight size={18}/></Link>)}<Link onClick={()=>setMobile(false)} href="/about">Our story</Link><Link onClick={()=>setMobile(false)} href="/contact">Contact us</Link></SheetContent></Sheet>
 <StoreMotion>{children}</StoreMotion><Footer/><CartDrawer/>{!s.live&&<div className="demo-label"><span>PREVIEW STORE</span> Checkout opens soon <Link href="/admin">Owner workspace <ArrowUpRight size={12}/></Link></div>}</>
}
export function CartLines(){const s=useStore();return <div className="cart-lines">{s.cart.map(line=>{const p=s.products.find(x=>x.id===line.productId);return <div className="cart-line" key={line.productId+line.variant}>{p&&<Link href={'/product/'+p.slug} onClick={()=>s.setCartOpen(false)}><img src={p.image} alt={p.name} width="100" height="110"/></Link>}<div className="cart-line-info"><Link href={p?'/product/'+p.slug:'/shop'} onClick={()=>s.setCartOpen(false)}>{p?.name??'Unavailable product'}</Link><p>{line.variant}</p><strong>{p?money(p.price):'Unavailable'}</strong><div className="quantity-control"><button aria-label="Decrease quantity" onClick={()=>s.quantity(line.productId,line.variant,line.quantity-1)}><Minus size={13}/></button><span>{line.quantity}</span><button aria-label="Increase quantity" onClick={()=>s.quantity(line.productId,line.variant,line.quantity+1)}><Plus size={13}/></button></div></div><button className="icon-button" aria-label="Remove item" onClick={()=>s.quantity(line.productId,line.variant,0)}><Trash2 size={17}/></button></div>})}</div>}
export function CartDrawer(){const s=useStore();const total=s.cart.reduce((a,x)=>a+(s.products.find(p=>p.id===x.productId)?.price??0)*x.quantity,0);return <Sheet open={s.cartOpen} onOpenChange={s.setCartOpen}><SheetContent className="cart-sheet"><SheetHeader><SheetTitle>Your bag <span className="muted">({s.cart.reduce((a,x)=>a+x.quantity,0)})</span></SheetTitle><SheetDescription>Good things, coming together.</SheetDescription></SheetHeader>{s.cart.length?<><div className="cart-scroll"><CartLines/></div><div className="cart-bottom"><div className="summary-line"><span>Subtotal</span><strong>{money(total)}</strong></div><p className="small muted">Delivery and any applicable taxes calculated at checkout.</p><Link className="button full" href="/checkout" onClick={()=>s.setCartOpen(false)}>Continue to checkout <ArrowRight size={18}/></Link><Link className="text-link centered" href="/cart" onClick={()=>s.setCartOpen(false)}>View your bag</Link></div></>:<div className="empty-state"><ShoppingBag size={42}/><h3>Your next favourite is waiting.</h3><p>Your bag is empty. Let's find something you'll love.</p><Link className="button" href="/shop" onClick={()=>s.setCartOpen(false)}>Explore the collection</Link></div>}</SheetContent></Sheet>}
function Footer(){const s=useStore();const [email,setEmail]=useState(''),[busy,setBusy]=useState(false);async function subscribe(e:FormEvent){e.preventDefault();setBusy(true);try{await api('newsletter',{email,consent:true});toast.success('You’re on the list. Welcome to Jedi’s Store.');setEmail('')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}return <><section className="newsletter"><div className="wrap newsletter-grid"><div><span className="eyebrow">STAY IN THE KNOW</span><h2>A little more good<br/>in your inbox.</h2><p>New finds, fresh collections, and the occasional good thing.</p></div><form onSubmit={subscribe}><label htmlFor="newsletter-email">Your email address</label><div><input id="newsletter-email" type="email" required placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><button aria-label="Subscribe to the newsletter" disabled={busy}><ArrowRight/></button></div><p>By subscribing, you agree to receive our emails. Unsubscribe anytime.</p></form></div></section><footer className="footer"><div className="wrap footer-grid"><div className="footer-brand"><Logo light/><p>Thoughtful finds. Everyday possibilities.<br/>A fresh perspective, from Ghana.</p><a href={brand.whatsapp} target="_blank" rel="noreferrer" className="footer-whatsapp">Let's talk <ArrowUpRight size={16}/></a></div><div><h3>Explore</h3><Link href="/shop">Shop all</Link>{categories.map(c=><Link key={c.slug} href={'/shop?category='+c.slug}>{c.name}</Link>)}</div><div><h3>Here to help</h3><Link href="/contact">Contact us</Link><Link href="/policies/shipping">Shipping & delivery</Link><Link href="/policies/returns">Returns & exchanges</Link><Link href="/policies/faq">Frequently asked questions</Link><Link href="/account">My account</Link></div><div><h3>Get in touch</h3><a href={'mailto:'+s.settings.email}><Mail size={15}/>{s.settings.email}</a><a href={'tel:'+brand.tel}><Phone size={15}/>{s.settings.phone}</a><span>Ghana · GHS</span><Link href="/about">The Jedi’s Store story <ArrowUpRight size={15}/></Link></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Jedi’s Store. Everyday, elevated.</span><div><Link href="/policies/privacy">Privacy</Link><Link href="/policies/terms">Terms</Link><Link href="/admin">Store management</Link></div></div></footer></>}
export function Benefits(){return <div className="benefits wrap"><div><span className="benefit-icon" aria-hidden="true"><Package/></span><span><strong>Thoughtfully selected</strong><small>Good finds for the everyday</small></span></div><div><span className="benefit-icon" aria-hidden="true"><ShieldCheck/></span><span><strong>Clear, simple shopping</strong><small>All the details before you decide</small></span></div><div><span className="benefit-icon" aria-hidden="true"><Headphones/></span><span><strong>A real person to help</strong><small>Talk to our team on WhatsApp</small></span></div></div>}
