import {runtimeValues} from '@/lib/runtime';
import {cookies} from 'next/headers';
import {products,type Product} from './catalog';
import {defaultSettings,type StoreData} from './types';
type Runtime=Record<string,string|undefined>;
export function config(){const e=runtimeValues() as Runtime;return {url:e.SUPABASE_URL??process.env.SUPABASE_URL??'',key:e.SUPABASE_PUBLISHABLE_KEY??process.env.SUPABASE_PUBLISHABLE_KEY??'',secret:e.SUPABASE_SECRET_KEY??process.env.SUPABASE_SECRET_KEY??'',origin:e.APP_ORIGIN??process.env.APP_ORIGIN??'',live:(e.STORE_LIVE??process.env.STORE_LIVE)==='true'};}
export class StoreError extends Error{constructor(message:string,public status=400){super(message)}}
export async function supa(path:string,options:RequestInit={},token?:string,privileged=false){const c=config();if(!c.url||!c.key)throw new StoreError('The store is getting ready. Please use our email or WhatsApp for now.',503);if(privileged&&!c.secret)throw new StoreError('This service is not connected yet. Please contact our team directly.',503);const h=new Headers(options.headers);h.set('apikey',privileged?c.secret:c.key);if(token)h.set('Authorization','Bearer '+token);if(options.body)h.set('Content-Type','application/json');const r=await fetch(c.url+path,{...options,headers:h,cache:'no-store'});const text=await r.text();let d;try{d=text?JSON.parse(text):null}catch{d=null}if(!r.ok){const msg=d?.msg??d?.message??d?.error_description??d?.error;if(r.status===401||r.status===403)throw new StoreError('Please sign in with an authorized account.',r.status);throw new StoreError(typeof msg==='string'?msg:'Unable to complete the request. Please try again.',r.status)}return d;}
export async function db(table:string,query='',token?:string,method='GET',body?:unknown,privileged=false){return supa('/rest/v1/'+table+(query?'?'+query:''),{method,headers:{Prefer:method==='POST'?'return=representation,resolution=merge-duplicates':'return=representation'},body:body?JSON.stringify(body):undefined},token,privileged)}
export async function rpc(name:string,body:unknown,token?:string,privileged=false){return supa('/rest/v1/rpc/'+name,{method:'POST',body:JSON.stringify(body)},token,privileged)}
export async function getStoreData():Promise<StoreData>{const c=config();if(!c.url||!c.key)return {products,settings:defaultSettings,configured:false,live:false};try{const [rows,settings]=await Promise.all([db('products','select=*&published=eq.true&order=created_at.desc'),db('store_settings','id=eq.main&select=value')]);return {products:rows as Product[],settings:{...defaultSettings,...(settings[0]?.value??{})},configured:true,live:c.live}}catch{throw new StoreError('The catalog is temporarily unavailable. Please try again shortly.',503)}}
export async function saveSession(d:{access_token?:string;refresh_token?:string;expires_in?:number}){if(!d.access_token)return;const jar=await cookies();const options={httpOnly:true,secure:true,sameSite:'lax' as const,path:'/'};jar.set('tv-access',d.access_token,{...options,maxAge:d.expires_in??3600});if(d.refresh_token)jar.set('tv-refresh',d.refresh_token,{...options,maxAge:60*60*24*30})}
export async function session(required=false){const jar=await cookies();let token=jar.get('tv-access')?.value;let user;try{if(token)user=await supa('/auth/v1/user',{},token)}catch{}if(!user){const refresh=jar.get('tv-refresh')?.value;if(refresh){try{const d=await supa('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:refresh})});await saveSession(d);token=d.access_token;user=d.user}catch{}}}if(required&&!user)throw new StoreError('Please sign in to continue.',401);return {token,user}}
export async function requireAdmin(){const s=await session(true);const allowed=await rpc('is_owner',{},s.token);if(!allowed)throw new StoreError('Owner access with two-step verification is required.',403);return s;}
export async function rateLimit(req:Request,path:string){const c=config();if(!c.secret)throw new StoreError('Store services are not connected yet. Please contact us by email or WhatsApp.',503);const raw=(req.headers.get('cf-connecting-ip')??'unknown')+':'+path;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)))).map(x=>x.toString(16).padStart(2,'0')).join('');const ok=await rpc('take_rate_limit',{p_key:hash,p_limit:path.startsWith('auth')?20:40},undefined,true);if(!ok)throw new StoreError('Please wait a minute before trying again.',429)}
export async function commerce(action:string,body:unknown,token?:string){const c=config();if(!c.live&&['checkout','refund'].includes(action))throw new StoreError('Checkout is not open yet. Your shopping bag has been kept.',503);return supa('/functions/v1/commerce',{method:'POST',body:JSON.stringify({...body as object,action})},token)}
